// Code generated by mockery v2.53.4. DO NOT EDIT.

package nslookup_mocks

import (
	config "github.com/Fivegen-LLC/sdwan-lib/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// IConfigService is an autogenerated mock type for the IConfigService type
type IConfigService struct {
	mock.Mock
}

type IConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *IConfigService) EXPECT() *IConfigService_Expecter {
	return &IConfigService_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function with no fields
func (_m *IConfigService) GetConfig() (config.Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (config.Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() config.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Config)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IConfigService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type IConfigService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *IConfigService_Expecter) GetConfig() *IConfigService_GetConfig_Call {
	return &IConfigService_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *IConfigService_GetConfig_Call) Run(run func()) *IConfigService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IConfigService_GetConfig_Call) Return(cfg config.Config, err error) *IConfigService_GetConfig_Call {
	_c.Call.Return(cfg, err)
	return _c
}

func (_c *IConfigService_GetConfig_Call) RunAndReturn(run func() (config.Config, error)) *IConfigService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewIConfigService creates a new instance of IConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConfigService {
	mock := &IConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
